// <auto-generated />
using System;
using CommentActivityLog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommentActivityLog.Infrastructure.Migrations
{
    [DbContext(typeof(CommentActivityLogDbContext))]
    [Migration("20260102180758_GetActivityLogs")]
    partial class GetActivityLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.ActivityLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("ActivityLog", (string)null);
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.CommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.GetActivityLogs", b =>
                {
                    b.Property<int>("activity_action")
                        .HasColumnType("int");

                    b.Property<DateTime>("activity_action_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("comment_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("task_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("GetActivityLogs");
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Task", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "لطفا در ویژوال استادیو یک پروژه وب جدید ایجاد کنید",
                            Title = "ایجاد پروژه ی جدید"
                        },
                        new
                        {
                            Id = 2,
                            Description = "لطفا معماری پروژه را تعیین کنید",
                            Title = "ایجاد معماری"
                        },
                        new
                        {
                            Id = 3,
                            Description = "لطفا مدل و موجودیت های خود را مشخص کنید",
                            Title = "ایجاد مدل"
                        });
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mahyaaa.khashkhashi@gmail.com",
                            UserName = "Mahya"
                        },
                        new
                        {
                            Id = 2,
                            Email = "HosseinDinarvand@gmail.com",
                            UserName = "Hosein"
                        },
                        new
                        {
                            Id = 3,
                            Email = "AlirezaEntezari@gmail.com",
                            UserName = "Alireza"
                        });
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.ActivityLogEntity", b =>
                {
                    b.HasOne("CommentActivityLog.Domain.Entities.CommentEntity", "Comment")
                        .WithMany("ActivitiyLogList")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.CommentEntity", b =>
                {
                    b.HasOne("CommentActivityLog.Domain.Entities.TaskEntity", "Task")
                        .WithMany("CommentList")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommentActivityLog.Domain.Entities.UserEntity", "User")
                        .WithMany("CommentList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.CommentEntity", b =>
                {
                    b.Navigation("ActivitiyLogList");
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.TaskEntity", b =>
                {
                    b.Navigation("CommentList");
                });

            modelBuilder.Entity("CommentActivityLog.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("CommentList");
                });
#pragma warning restore 612, 618
        }
    }
}
